name: permisapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-245.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  cached_network_image: ^3.2.3
  http: ^0.13.5
  easy_localization: ^3.0.1
  images_picker:
  app_settings: ^4.2.0
  line_awesome_flutter: ^2.0.0
  flutter_settings_screens:
  flutter_image_compress: ^2.0.3
  multi_select_flutter: ^4.1.3
  connectivity_plus: ^3.0.3
  connectivity: ^3.0.3
  equatable: ^2.0.5
  network_handler: ^1.0.1
  auth: ^8.2.0+2
  url_launcher: ^6.1.10
  flutter_session_manager: ^1.0.2
  get_storage: ^2.1.1
  shared_preferences: ^2.1.0
  awesome_notifications: ^0.7.4+1
  flutter_local_notifications: ^14.1.0
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  cupertino_icons: ^1.0.2

  boxicons: ^2.1.3
  wave: ^0.2.2

  flutter_locales:
  persistent_bottom_nav_bar: ^4.0.2
  percent_indicator: ^4.0.0
  carousel_slider: ^4.0.0
  onboarding: ^3.1.0
  flutter_svg: ^1.0.3
  getwidget: ^3.0.1
  iconly: ^1.0.1
  page_transition: ^2.0.5
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  fl_chart: ^0.55.0
  im_stepper: ^1.0.1+1
  achievement_view: ^1.0.0
  focused_menu: ^1.0.5
  email_validator: ^2.0.1
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  intl:
  camera: ^0.10.0+1
  permission_handler: ^10.0.0
  after_layout: ^1.2.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  dropdown_search: ^5.0.2
  timeago: ^3.2.2
  jiffy: ^5.0.0
  onesignal_flutter: ^3.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/check.png"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/

  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
